"""trying w vishaal

Revision ID: 19fd425437c2
Revises: 
Create Date: 2021-07-29 13:02:24.113037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19fd425437c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commres',
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('delivery_address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('donations_sent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('resident_id')
    )
    op.create_table('farmer',
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('farm_location', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('donations_received', sa.Integer(), nullable=True),
    sa.Column('contribution_dropoff', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('farmer_id')
    )
    op.create_table('nporep',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('delivery_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('offering',
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('offering_type', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('total_inventory', sa.Integer(), nullable=True),
    sa.Column('available_inventory', sa.Integer(), nullable=True),
    sa.Column('usda_organic', sa.Boolean(), nullable=True),
    sa.Column('in_weeks', sa.Integer(), nullable=True),
    sa.Column('side_effects', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('offering_id')
    )
    op.create_table('order',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_location', sa.String(length=200), nullable=True),
    sa.Column('handoff_type', sa.Boolean(), nullable=True),
    sa.Column('commres_id', sa.Integer(), nullable=True),
    sa.Column('nporep_id', sa.Integer(), nullable=True),
    sa.Column('offering_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commres_id'], ['commres.resident_id'], ),
    sa.ForeignKeyConstraint(['nporep_id'], ['nporep.employee_id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.offering_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    op.drop_table('offering')
    op.drop_table('nporep')
    op.drop_table('farmer')
    op.drop_table('commres')
    # ### end Alembic commands ###
