"""changed order object name to avoid sql keyword confusion

Revision ID: 2ba8b9511008
Revises: 69e4f831d96c
Create Date: 2021-07-29 13:40:25.392079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ba8b9511008'
down_revision = '69e4f831d96c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_box',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_location', sa.String(length=200), nullable=True),
    sa.Column('handoff_type', sa.Boolean(), nullable=True),
    sa.Column('commres_id', sa.Integer(), nullable=True),
    sa.Column('nporep_id', sa.Integer(), nullable=True),
    sa.Column('offering_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commres_id'], ['commres.resident_id'], ),
    sa.ForeignKeyConstraint(['nporep_id'], ['nporep.employee_id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.offering_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.drop_table('order')
    op.add_column('offering', sa.Column('usage_time_limit', sa.Integer(), nullable=True))
    op.drop_column('offering', 'in_weeks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offering', sa.Column('in_weeks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('offering', 'usage_time_limit')
    op.create_table('order',
    sa.Column('order_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('delivery_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivery_location', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('handoff_type', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('commres_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nporep_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('offering_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['commres_id'], ['commres.resident_id'], name='order_commres_id_fkey'),
    sa.ForeignKeyConstraint(['nporep_id'], ['nporep.employee_id'], name='order_nporep_id_fkey'),
    sa.ForeignKeyConstraint(['offering_id'], ['offering.offering_id'], name='order_offering_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', name='order_pkey')
    )
    op.drop_table('order_box')
    # ### end Alembic commands ###
