"""empty message

Revision ID: 69e4f831d96c
Revises: 19fd425437c2
Create Date: 2021-07-29 13:08:04.923516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69e4f831d96c'
down_revision = '19fd425437c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmer_contribution',
    sa.Column('farm_contr_id', sa.Integer(), nullable=False),
    sa.Column('harvest_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('bake_date', sa.DateTime(), nullable=True),
    sa.Column('dried_date', sa.DateTime(), nullable=True),
    sa.Column('make_date', sa.DateTime(), nullable=True),
    sa.Column('dropoff_location', sa.String(length=200), nullable=True),
    sa.Column('contributing_farmer_id', sa.Integer(), nullable=True),
    sa.Column('relevant_offering_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contributing_farmer_id'], ['farmer.farmer_id'], ),
    sa.ForeignKeyConstraint(['relevant_offering_id'], ['offering.offering_id'], ),
    sa.PrimaryKeyConstraint('farm_contr_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farmer_contribution')
    # ### end Alembic commands ###
