"""found the user table bug

Revision ID: 76877a959ab9
Revises: 
Create Date: 2021-08-10 21:51:15.868354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76877a959ab9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('preferred_name', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=10), nullable=False),
    sa.Column('donations_sent', sa.Integer(), nullable=True),
    sa.Column('donations_received', sa.Integer(), nullable=True),
    sa.Column('contribution_dropoff', sa.Boolean(), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('delivery_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('offering_batch',
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('total_inventory', sa.Integer(), nullable=True),
    sa.Column('available_inventory', sa.Integer(), nullable=True),
    sa.Column('usda_organic', sa.Boolean(), nullable=True),
    sa.Column('usage_time_limit', sa.Integer(), nullable=True),
    sa.Column('side_effects', sa.String(length=300), nullable=True),
    sa.Column('contribution_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('bake_date', sa.DateTime(), nullable=True),
    sa.Column('dried_date', sa.DateTime(), nullable=True),
    sa.Column('make_date', sa.DateTime(), nullable=True),
    sa.Column('dropoff_location', sa.String(length=200), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('offering_id')
    )
    op.create_table('order_box',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_location', sa.String(length=200), nullable=True),
    sa.Column('handoff_type', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('offering_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['offering_batch.offering_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.user_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('offering_order',
    sa.Column('contents_id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['offering_batch.offering_id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order_box.order_id'], ),
    sa.PrimaryKeyConstraint('contents_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offering_order')
    op.drop_table('order_box')
    op.drop_table('offering_batch')
    op.drop_table('category')
    op.drop_table('app_user')
    # ### end Alembic commands ###
