"""added category model for O2M w offerings

Revision ID: 81253e0ea61b
Revises: 2ba8b9511008
Create Date: 2021-07-29 14:44:37.334744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81253e0ea61b'
down_revision = '2ba8b9511008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.add_column('offering', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'offering', 'category', ['category_id'], ['category_id'])
    op.drop_column('offering', 'offering_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offering', sa.Column('offering_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'offering', type_='foreignkey')
    op.drop_column('offering', 'category_id')
    op.drop_table('category')
    # ### end Alembic commands ###
