"""round 3 erds and models attempt

Revision ID: a1b06b108a51
Revises: 
Create Date: 2021-08-02 12:04:37.522024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b06b108a51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('category_title', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('commres',
    sa.Column('resident_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('delivery_address', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('donations_sent', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('resident_id')
    )
    op.create_table('farmer',
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('farm_location', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('donations_received', sa.Integer(), nullable=True),
    sa.Column('contribution_dropoff', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('farmer_id')
    )
    op.create_table('nporep',
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=10), nullable=True),
    sa.Column('delivery_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('order_box',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_location', sa.String(length=200), nullable=True),
    sa.Column('handoff_type', sa.Boolean(), nullable=True),
    sa.Column('commres_id', sa.Integer(), nullable=True),
    sa.Column('nporep_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['commres_id'], ['commres.resident_id'], ),
    sa.ForeignKeyConstraint(['nporep_id'], ['nporep.employee_id'], ),
    sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('offering_batch',
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('total_inventory', sa.Integer(), nullable=True),
    sa.Column('available_inventory', sa.Integer(), nullable=True),
    sa.Column('usda_organic', sa.Boolean(), nullable=True),
    sa.Column('usage_time_limit', sa.Integer(), nullable=True),
    sa.Column('side_effects', sa.String(length=300), nullable=True),
    sa.Column('harvest_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('bake_date', sa.DateTime(), nullable=True),
    sa.Column('dried_date', sa.DateTime(), nullable=True),
    sa.Column('make_date', sa.DateTime(), nullable=True),
    sa.Column('dropoff_location', sa.String(length=200), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('order_box_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.category_id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer.farmer_id'], ),
    sa.ForeignKeyConstraint(['order_box_id'], ['order_box.order_id'], ),
    sa.PrimaryKeyConstraint('offering_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offering_batch')
    op.drop_table('order_box')
    op.drop_table('nporep')
    op.drop_table('farmer')
    op.drop_table('commres')
    op.drop_table('category')
    # ### end Alembic commands ###
