"""update user table name

Revision ID: d28e24f1fc37
Revises: 76877a959ab9
Create Date: 2021-08-12 20:17:32.110967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28e24f1fc37'
down_revision = '76877a959ab9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('email', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'email')
    # ### end Alembic commands ###
